import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Slider component",
  description: "Generated by create next app",
};
const diatypeFont = localFont({
  src: "../../public/fonts/ABCDiatypeRoundedVariable-Trial.ttf",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${diatypeFont.className}`}>{children}</body>
    </html>
  );
}
